name: mmlu_eval
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.1
  - pandas
  - tqdm
  - pip
  - ipython
  - jupyter
  - jupyterlab
  - notebook
  - ipywidgets
  - nbformat
  - nbclient
  - pip:
    - transformers
    - datasets
    - accelerate
    - jupyter-archive
    - jupyter-resource-usage
    - jupyter-server
    - ipykernel
